name: Paul's Website
title: Paul Crews
author: Paul Crews

collections:
  sections:
    output: false

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
